### ISSUE TITLE
Getting an "ImportError: cannot import name 'ArgSpec' from 'inspect'" Error

### ISSUE THREAD

**Issue by GeorgAubele** [agronholm/sqlacodegen#258] opened 2023-03-10 10:44 UTC
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

Can't use sqlacodegen, because I'm getting this error everytime I start it, even with

sqlacodegen --help

Error Messages as folllows:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\Programme\Python\Scripts\sqlacodegen.exe\__main__.py", line 4, in <module>
  File "E:\Programme\Python\Lib\site-packages\sqlacodegen\main.py", line 11, in <module>
    from sqlacodegen.codegen import CodeGenerator
  File "E:\Programme\Python\Lib\site-packages\sqlacodegen\codegen.py", line 9, in <module>
    from inspect import ArgSpec
ImportError: cannot import name 'ArgSpec' from 'inspect' (E:\Programme\Python\Lib\inspect.py)

### Use case

I want to use sqlacodegen and don't know how to file a bug report.

**Comment by 497100512** [comment] 2023-04-02 08:11
Comment on this code
![image](https://user-images.githubusercontent.com/45337085/229340706-479fdf00-057c-4f26-94d4-b01c0a68f2f0.png)
success

**Comment by thinkjrs** [comment] 2023-05-30 19:41
@agronholm Can we close this issue? It seems like an _exact dupe of #239_, for which there's a clear/simple solution (to which you referred herein, using the release candidate 3.0).

**Comment by agronholm** [comment] 2023-05-30 19:42
Yup.

**Closed by agronholm** 2023-05-30 19:42 UTC
Labels: enhancement
