### ISSUE TITLE
generated Error when there is computed virtual column

### ISSUE THREAD

**Issue by BridgeWind** [agronholm/sqlacodegen#168] opened 2021-12-10 09:13 UTC
![image](https://user-images.githubusercontent.com/45143983/145548078-95233561-5fad-460d-8628-5dd45bf2a0e3.png)
Column should be in the order like Column(*args,**kwargs), so for generating column like this, unique = True should be in the place after "Computed(......)" 
It should be like this:
 Column(CHAR(32), Computed("(md5(concat_ws('.',ifnull(`position_id`,0)，ifnull(`h)", persisted=False),unique=True)

**Comment by agronholm** [comment] 2021-12-10 09:14
This is on 3.0.0b2?

**Comment by BridgeWind** [comment] 2021-12-10 09:26
sqlacodegen==2.3.0 xD

**Comment by agronholm** [comment] 2021-12-10 09:28
Would you mind trying with the beta?

**Comment by BridgeWind** [comment] 2021-12-10 09:32
I'll try xD, just notice we got beta version... orz

**Comment by BridgeWind** [comment] 2021-12-10 09:43
Great! Works fine for 3.0.0b2

**Comment by agronholm** [comment] 2021-12-11 15:56
Closing as duplicate of #165.

**Closed by agronholm** 2021-12-11 15:56 UTC
Labels: bug
