### ISSUE TITLE
Option --generator only works in pre-release package

### ISSUE THREAD

**Issue by gregbrowndev** [agronholm/sqlacodegen#269] opened 2023-06-12 19:53 UTC
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Sqlacodegen version

2.3.0.post1

### SQLAlchemy version

1.4.48

### RDBMS vendor

PostgreSQL

### What happened?

Trying to follow README:

```
sqlacodegen --generator dataclasses sqlite:///database.db
```

Error:

```
sqlacodegen: error: unrecognized arguments: --generator sqlite:///database.db
```

It does work when `3.0.0rc2` installed with pre-release allowed:

```
pip install --pre sqlacodegen
```

Should ideally keep README and docs in branch until version is released to avoid confusion.

Cheers though!

### Database schema for reproducing the bug

N/A

**Comment by agronholm** [comment] 2023-06-20 13:15
Yeah, not a bug. The final release was not supposed to take this long, but I've been bogged down in other projects.

**Comment by crazydiamondzgy** [comment] 2023-10-30 03:58
same issue, but i found it works normally in 3.0.0rc3

**Comment by agronholm** [comment] 2024-12-28 13:30
Closing as a non-issue.

**Closed by agronholm** 2024-12-28 13:30 UTC
Labels: bug
