### ISSUE TITLE
[Bug] Ordering issue

### ISSUE THREAD

**Issue by WhoAteDaCake** [agronholm/sqlacodegen#178] opened 2022-01-17 21:45 UTC
When generating relationships, it can create an issue where optional fields exist before, which leads to 

```python

    parent: Optional[Any] = field(default=None, metadata={'sa': Column(ForeignKey('paths.uuid', ondelete='CASCADE'), index=True)})
    finished: Optional[datetime] = field(default=None, metadata={'sa': Column(DateTime)})

    parent: Optional[Any] = field(default=None, metadata={'sa': Column(ForeignKey('paths.uuid', ondelete='CASCADE'), index=True)})
    finished: Optional[datetime] = field(default=None, metadata={'sa': Column(DateTime)})

    paths: Optional[Paths] = field(default=None, metadata={'sa': relationship('Paths', remote_side=[uuid], back_populates='paths_reverse')})
    paths_reverse: Optional[List[Paths]] = field(default_factory=list, metadata={'sa': relationship('Paths', remote_side=[parent], back_populates='paths')})
    workflows: Workflows = field(metadata={'sa': relationship('Workflows', back_populates='paths')})
```

Which will cause a throw with 
>     raise TypeError(f'non-default argument {f.name!r} ' TypeError: non-default argument 'workflows' follows default argument

**Comment by agronholm** [comment] 2022-01-18 08:18
Duplicate of #164.

**Closed by agronholm** 2022-01-18 08:18 UTC

**Comment by WhoAteDaCake** [comment] 2022-01-18 11:33
I thought I'd report it as a separate issue since, this is happening within the relationships group

**Comment by agronholm** [comment] 2022-01-18 11:34
The root cause is the same: columns are ordered correctly in this fashion (I think) but relationships should all have a default, and they currently don't.
