### ISSUE TITLE
Unable to generate combined UniqueKeyConstraint (for multiple columns) in the declarative model.

### ISSUE THREAD

**Issue by Vrushank-21** [agronholm/sqlacodegen#244] opened 2023-01-19 09:20 UTC
I have a Unique key constraint on multiple columns for a few tables in my database but it does not show up in the declarative model generated. Please help with this issue.

**Comment by agronholm** [comment] 2023-01-19 09:21
What version of sqlacodegen did you use? Have you tried the latest pre-release version?

**Comment by Vrushank-21** [comment] 2023-01-19 09:22
Yes.  I have used the version 3.0.0rc1

**Comment by agronholm** [comment] 2023-01-19 09:23
Ok, show me how I can reproduce the problem on my end.

**Comment by Vrushank-21** [comment] 2023-01-19 09:34
DDL:
CREATE TABLE DUMMY
(
    attr1    integer  NOT NULL ,
    attr2    char    NOT NULL ,
    attr3   datetime   NOT NULL
   
   CONSTRAINT pk1 PRIMARY KEY (attr3),
   CONSTRAINT uk UNIQUE(attr1, attr2, attr3)
)

for the above table the resulting declarative model should have the following __table_args__:
__table_args__ = (
    PrimaryKeyConstraint('attr3', name = 'pk1')
    UniqueKeyConstraint( 'attr1','attr2','attr3', name='uk')
)

**Comment by agronholm** [comment] 2023-01-19 09:35
What RDBMS are you using?

**Comment by Vrushank-21** [comment] 2023-01-19 09:36
Sqlite3

**Comment by agronholm** [comment] 2023-01-19 09:41
This is what I get:
```python3
from sqlalchemy import CHAR, Column, DateTime, Integer, PrimaryKeyConstraint, UniqueConstraint
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class DUMMY(Base):
    __tablename__ = 'DUMMY'
    __table_args__ = (
        PrimaryKeyConstraint('attr3', name='pk1'),
        UniqueConstraint('attr1', 'attr2', 'attr3', name='uk')
    )

    attr1 = Column(Integer, nullable=False)
    attr2 = Column(CHAR, nullable=False)
    attr3 = Column(DateTime)
```

**Comment by Vrushank-21** [comment] 2023-01-19 09:44
Yes. This is exactly what I wanted. I'm not sure what the issue is on my end. I'll check and get back. Thanks a lot!

**Comment by agronholm** [comment] 2023-01-19 09:44
What version of SQLAlchemy did you use?

**Comment by Vrushank-21** [comment] 2023-01-19 09:45
1.4.41

**Comment by agronholm** [comment] 2023-01-19 09:47
[testdb.zip](https://github.com/agronholm/sqlacodegen/files/10455510/testdb.zip)
Could you try against the database in the attached zip file?

**Comment by Vrushank-21** [comment] 2023-01-19 10:03
from sqlalchemy import CHAR, Column, DateTime, Integer, PrimaryKeyConstraint, UniqueConstraint
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class DUMMY(Base):
    __tablename__ = 'DUMMY'
    __table_args__ = (
        PrimaryKeyConstraint('attr3', name='pk1'),
        UniqueConstraint('attr1', 'attr2', 'attr3', name='uk')
    )

    attr1 = Column(Integer, nullable=False)
    attr2 = Column(CHAR, nullable=False)
    attr3 = Column(DateTime)

**Comment by agronholm** [comment] 2023-01-19 10:04
So you get the same results as I do? Are you sure that your original DB did actually not have those unique constraints? How did you manage to reproduce the problem with the instructions you gave me?

**Comment by Vrushank-21** [comment] 2023-01-19 10:08
The only thing I changed just now was the sqlalchemy version (to 1.4.46).

**Comment by Vrushank-21** [comment] 2023-01-19 10:35
Hey. Apologies. I just tried it on another PC with python 3.10. It doesn't give the unique constraint.
`from sqlalchemy import CHAR, Column, DateTime, Integer, PrimaryKeyConstraint, UniqueConstraint
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class DUMMY(Base):
    __tablename__ = 'DUMMY'
    __table_args__ = (
        PrimaryKeyConstraint('attr3', name='pk1'),
   )

    attr1 = Column(Integer, nullable=False)
    attr2 = Column(CHAR, nullable=False)
    attr3 = Column(DateTime)
`

**Comment by agronholm** [comment] 2023-01-19 10:36
Can you confirm the sqlite3 and sqlalchemy versions on that PC?

**Comment by Vrushank-21** [comment] 2023-01-19 10:41
I am running sqlite scripts in SqliteStudio 3.2.1 and the sqlalchemy version is 1.4.46

**Comment by agronholm** [comment] 2023-01-19 10:43
I'm talking about the `sqlite3` library on your system, available from `sqlite3.sqlite_version`.

I tried this on Python 3.10.9 on latest SQLAlchemy and SQLite3 3.40.0, and it worked fine.

**Comment by Vrushank-21** [comment] 2023-01-19 10:45
Oh. The sqlite3 version I'm using is 3.35.5

**Comment by agronholm** [comment] 2023-01-19 10:46
> Oh. The sqlite3 version I'm using is 3.35.5

On the machine where it generated the unique constraint successfully, or on the one where it failed?

**Comment by Vrushank-21** [comment] 2023-01-19 10:47
The one where it failed

**Comment by agronholm** [comment] 2023-01-19 10:55
What about the one where it succeeded?

**Comment by Vrushank-21** [comment] 2023-01-19 11:02
3.37.2

**Comment by agronholm** [comment] 2023-01-19 11:04
Hard to say if that difference is the cause, but at least it's not caused by sqlacodegen, so I'm closing this.

**Closed by agronholm** 2023-01-19 11:04 UTC

**Comment by Vrushank-21** [comment] 2023-01-19 11:05
Sure. I'll try figuring out the problem. Thanks a lot for the help.
