### ISSUE TITLE
Implement bi-directional relationships

### ISSUE THREAD

**Issue by t-o-o-m** [agronholm/sqlacodegen#108] opened 2020-01-03 10:31 UTC
Creating a bidirectional many-to-many relationship seems to be impossible with sqlacodegen.

# Desired model
```
association_table = Table('association', Base.metadata,
    Column('left_id', Integer, ForeignKey('left.id')),
    Column('right_id', Integer, ForeignKey('right.id'))
)

class Parent(Base):
    __tablename__ = 'left'
    id = Column(Integer, primary_key=True)
    children = relationship(
        "Child",
        secondary=association_table,
        back_populates="parents")

class Child(Base):
    __tablename__ = 'right'
    id = Column(Integer, primary_key=True)
    parents = relationship(
        "Parent",
        secondary=association_table,
        back_populates="children")
```

# Model created by sqlacodegen
```
association_table = Table('association', Base.metadata,
    Column('left_id', Integer, ForeignKey('left.id')),
    Column('right_id', Integer, ForeignKey('right.id'))
)

class Parent(Base):
    __tablename__ = 'left'
    id = Column(Integer, primary_key=True)
    children = relationship("Child",
                    secondary=association_table)

class Child(Base):
    __tablename__ = 'right'
    id = Column(Integer, primary_key=True)
```

A single backref definition in the parent would suffice according to https://docs.sqlalchemy.org/en/13/orm/basic_relationships.html?highlight=relationship#basic-relationship-patterns

**Comment by osmnorhn** [comment] 2020-06-29 11:12
Is there any updates regarding to this situation ?
Is there any plans to support bi-directional relationships ?

**Comment by adyah-cisco** [comment] 2021-07-19 11:14
Will this be fixed with the PR that I see? Would love to have this implemented.

**Comment by agronholm** [comment] 2021-07-19 14:53
I will try to add it in v3.0. Most of the work for that version is done, so the process of adding features can now resume.

**Comment by agronholm** [comment] 2021-07-23 12:54
I have code for this now, still 13 failing tests but getting there. It will be in v3.0.

**Comment by agronholm** [comment] 2021-07-23 12:54
Oh, and I'm making it the default.

**Comment by agronholm** [comment] 2021-07-24 21:17
3 failing tests left. Problems are focused on one-to-many relationships which are either self referential or have multiple foreign keys between the source and target tables.

**Closed** 2021-07-26 10:52 UTC
Labels: enhancement

**Comment by sdementen** [comment] 2023-03-23 09:05
The issue is closed yet as my request is tightly linked I post it here (I can make a new issue if you prefer)
Would it be possible to have both sidea of the relationship to be created so that IDEs can provide autocompletion for both sides?
